### ISSUE TITLE
[BUG] api.swap is not a function

### ISSUE THREAD

**Issue by CRSylar** [bigskysoftware/htmx-extensions#67]
Hi !

i'm having problems using the extension.

i've got this error
```
TypeError: api.swap is not a function
    at swap (sse.js:283:9)
    at EventSource.listener (sse.js:122:11)
```

seems like the swap method in the call for api.swap do not exists..
i'm using the unpkg link, so i believe is the latest release

note. i've got this error regardless of using named events o the "message" one

**Comment by Telroshan** [comment]
Hey, seems you got it figured out as you closed the issue, but feel free to share what was the cause/solution so that if others stumble on the same problem, they might fix it thanks to your experience!

Looking at the error above, the only thing that comes to mind is if you were using htmx 1 with the extensions of this repo, that use the htmx2-introduced `swap` method (so if you're still using htmx 1, indeed `api.swap` doesn't exist).
What that the cause, or was the problem somewhere else?
