### ISSUE TITLE
Am I doing something wrong or is the `preload` extension asking the server for pages without the necessary headers?

### ISSUE THREAD

**Issue by frederikhors** [bigskysoftware/htmx-extensions#89]
Sorry to bother you,

I'm trying these days `htmx` for the first time (CONGRATULATIONS!) and I'm trying right now the `preload` extension.

Is it correct that the preload today doesn't send headers like `hx-request` and `hx-target`?

If this is correct I'm wondering how can such an extension be useful without these headers?

The server will return a whole page on each preload-trigger and my navigation between pages in browser using htmx will never take advantage of that preload.

Simply because what I'm asking to the server are fragments and not entire pages.

Am I wrong?

**Comment by frederikhors** [comment]
> the method you're suggesting (using the same endpoint and determining what to answer based on headers) wouldn't work very well with preload.

Why not?

Right now [as very well explained here](https://htmx.org/docs/#caching) I'm using the same endpoint choosing what to render (between full or fragment) based on `hx-request` header.

**Comment by Telroshan** [comment]
Oops indeed, totally forgot about `Vary`, you're totally right!
Then I don't see why the extension should _not_ send the htmx headers, so if you'd like to suggest an implementation and open a PR to address that, feel free to do so!

**Comment by marisst** [comment]
@frederikhors The preload extension is sending `HX-Request` headers when the element target is anticipated to be loaded by HTMX. This was not the case in some earlier versions of the extension, but since the addition of `source: node` [here](https://github.com/bigskysoftware/htmx-extensions/blob/457da4b34ed330edd641d56ea7d85a12f2099cf9/src/preload/preload.js#L49) it has been fixed.

Please note that `<a href="/link" preload>` is not anticipated to be loaded by HTMX, and preload will therefore issue a regular XML request without `HX-Request` headers. But for elements with `hx-get` or `data-hx-get` attribute `HX-Request` header will be passed along with other hx values.

A more tricky case is if you use `hx-boost="true"` property. The current version of the extension will not add `HX-Request` headers to boosted hyperlinks e.g. `<body hx-boost="true"><a href="/link" preload>Link</a></body>`. #106 is fixing it, and if you would like to use that version of the extension already now you can access it [here](https://github.com/marisst/htmx-extensions/blob/main/src/preload/preload.js).

**Comment by Telroshan** [comment]
@frederikhors could you confirm if #106 addresses all your concerns ? (new extension's version is not yet published, so you'd have to use the file directly from the repo and not the npm's one!)

**Comment by frederikhors** [comment]
@Telroshan I'm not using htmx unfortunately.

**Comment by Telroshan** [comment]
Oh I see, then I'm closing this as it sounds like solved by #106 , feel free to reopen / ping if anyone encounters this again!
