### ISSUE TITLE
Preload: stopping event propagation when priming a cache? 

### ISSUE THREAD

**Issue by meln1k** [bigskysoftware/htmx-extensions#90]
I have a spinner overlay which is triggered via `htmx:beforeRequest` and `htmx:afterRequest` events, and when I use the preload extension with hx-get, the "cache priming" request sends those events and this triggers the overlay (which is undesirable since it happens on mouseover). 

Shouldn't those events be caught and prevented from propagation (to keep the cache priming side-effects free)?

**Comment by Telroshan** [comment]
There had been a PR about that on the htmx repo (back when extensions were in the same repo), see https://github.com/bigskysoftware/htmx/pull/1511

Seems it got closed due to inactivity but the suggested change had been approved.
If you'd like to look into it and submit a bugfix PR, feel free to do so, PR welcome!

**Comment by meln1k** [comment]
Cool, I created a PR #91 which should add side-effect free handling for hx-get requests.

**Comment by Telroshan** [comment]
Fixed in #106
